# Generated by Django 5.0.6 on 2024-07-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ves', models.FloatField(default=3.6)),
                ('dlina', models.FloatField(default=150)),
                ('unitl', models.CharField(default='cm', max_length=10)),
                ('razmer_romba', models.FloatField(default=3.6)),
                ('unitr', models.CharField(default='mm', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
